## NUMPY (AI FELLOWSHIP -DAY 2- pulchowk.ai)
### Course Structure

### Numpy  =  ndarray + ufunc (universal functions) 
### 1. Creating 1D and 2D array
### 2. Random Number Generation
### 3. Shaping 
### 4. Indexing and Slicing
### 5. Linear Algebra Overview

In [ ]:
# Import NUMPY
import numpy as np

# 1. creating 1 D and 2D array

In [ ]:
list = [2,3,9]

In [ ]:
list

In [ ]:
arr = np.array(list) #1D array

In [ ]:
#numpy is made up of ndarrays
print(arr,type(arr))

In [ ]:
#two dimensional array
matrix = [[1,2,3], [4,5,6], [7,8,9]]
my_arr = np.array(matrix) 
print(my_arr)

In [45]:
#using built in functions to create numpy array
# Start, Stop, Step
# arange creates array from start to stop-1 with step size
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [44]:
# n x n identity matrix 
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
np.linspace(0,5,10)
# linspace returns evenly spaced 10 points from 0 to 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [43]:
float_zeros = np.zeros(3)
int_zeros = np.zeros(3,dtype = int)
print(float_zeros)
print(int_zeros)

[0. 0. 0.]
[0 0 0]


In [ ]:
zero_mat=np.zeros((2,3))
zero_mat

# 2. Random number generation

In [47]:
# rand generates random numbers between 0 and 1
np.random.rand(5) 

array([0.31949295, 0.68551099, 0.5266383 , 0.28985233, 0.67664581])

In [49]:
# Assignment
# a function that generates n random numbers between p and q
def myrand(n,p,q):
    return p+np.random.rand(n)*(q-p)


myrand(2,10,20)

array([17.56088706, 17.79650167])

In [ ]:
# random matrix of size 5 x 5
np.random.rand(5,5)

In [ ]:
#randn generates random numbers from normal distribution
np.random.randn(2) 

In [ ]:
#randint generates random number in between 1 and 50
np.random.randint(1,50)

In [ ]:
#generates  5 random numbers from 1 to 200
np.random.randint(1,200,5)

# seed() gives same random number 

## The method seed() sets the integer starting value used in generating random numbers.
## Call this function before calling any other random module function.


 (pseudo-)random numbers work by starting with a number (the seed), 
 multiplying it by a large number, then taking modulo of that product. 
 The resulting number is then used as the seed to generate the next "random" number.
 When you set the seed (every time),  it does the same thing every time, giving you the same numbers.

In [ ]:
np.random.seed(10)
np.random.rand(2)


In [ ]:
np.random.seed(10)
np.random.random((1,5))

# 3. Shaping 

In [50]:
# Generate an array of size 15
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [51]:
# array shape
arr.shape

(15,)

For a 1D array, the shape would be (n,) where n is the number of elements in your array.

For a 2D array, the shape would be (n,m) where n is the number of rows and m is the number of columns in your array.

In [52]:
#reshaping the array
arr.reshape(5,3)
## Remember the number of array elements must be same in matrix too.


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
# What will be the result
arr.reshape(5,5)

In [ ]:
# what will be result
arr

In [53]:
# Multidimensional Arrays
np.arange(0,24,2).reshape(3,4)

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [ ]:
arr.max() ## maximum value of array

In [ ]:
arr.min() ## minimum value of array

In [54]:
print('Mean :', arr.mean() , ' Standard Deviation : ',  arr.std())

Mean : 7.0  Standard Deviation :  4.320493798938574


In [55]:
mat=np.array(([1,2],[3,4],[5,6]))

In [56]:
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [57]:
#finding shape of array 
mat.shape
## matrix of size 3 x 2 i.e. 3 rows and 2 columns

(3, 2)

In [58]:
mat=mat.reshape(2,3)
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
## shape of mat 
mat.shape

(2, 3)

In [60]:
#datatype in array
arr.dtype

dtype('int64')

# 4. Indexing and Slicing


In [61]:
arr = np.arange(0,10)

In [62]:
# array indexing
arr[1]

1

In [63]:
arr[1:5] #slicing

array([1, 2, 3, 4])

In [64]:
arr[:5]

array([0, 1, 2, 3, 4])

In [65]:
arr[0:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
## inserting value
arr[0] = 100 
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [68]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Copying 

In [69]:
new_arr = arr[0:6]
new_arr

array([0, 1, 2, 3, 4, 5])

In [70]:
new_arr[:] = 99

In [71]:
new_arr

array([99, 99, 99, 99, 99, 99])

In [72]:
#Only address is sent not values
arr 

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [73]:
# There is copy function to copy array
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [ ]:
arr_copy[6:] =100
arr_copy

In [ ]:
#now we can see the values have been copied not address
arr

## Indexing matrix

In [ ]:
#2D array

arr_mat = np.array([[1,2,3], [0,5,9], [3,5,4]])
arr_mat

In [ ]:
#indexing
arr_mat[0,0] ## 1st row 1st column element

In [ ]:
arr_mat[0][0]

In [ ]:
arr_mat[0] ## gives first row

In [ ]:
arr_mat[2,2] ## 3rd row 3rd column element

In [ ]:
arr_mat

In [ ]:
## slicing 2D array
arr_mat[:2,1:]

In [ ]:
## slicing 2D array
arr_mat[:3, 1:2]

In [ ]:
## slicing 2D array

arr_mat[:, 2:3]

## 5. Linear Algebra
#### Basic Overview

#### Ndarray Operations (Broadcasting)

In [2]:
import numpy as np
arr = np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [3]:
# The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations.
# ndarray uses broadcasting when operated with a scalar i.e every value gets affected
print(arr+1)
print(arr*2)
print(arr//2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]]
[[0 0 1 1]
 [2 2 3 3]
 [4 4 5 5]
 [6 6 7 7]]


In [4]:
# what about arrays op arrays
# similar to matrix
arr2 = arr+arr
arr2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [42]:
# multiplication only works when dimensions satisfy
#ndarrrays are operations basically matrix operations 
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[3,4],[5,6]])
mat1*mat2


array([[ 3,  8],
       [15, 24]])

In [5]:
#transpose
arr.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

#### Filtering Data

In [6]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
bool_value = arr >= 5
bool_value

In [ ]:
arr[bool_value]

In [7]:
#easier way
arr[arr>=8]

array([8, 9])

#### Linear Algebra

In [8]:
arr = np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [9]:
#determinant
np.linalg.det(arr)

-2.0000000000000004

In [10]:
#inverse
np.linalg.inv(arr)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [12]:
# matrix and Vector Operations

#Vector dotproduct and cos angle
a = np.array([1,2,3])
b = np.array([1,5,7])
amag = np.linalg.norm(a)  ## absolute value
bmag = np.linalg.norm(b) 
cos_angle = a.dot(b) / ( amag * bmag)
cos_angle



0.9875414397573881

In [28]:
#a.dot(b)
np.dot(a,b)

32

In [14]:
cosangle = np.arccos(cos_angle)  ## cos inverse value
cosangle

0.15801592211305823

In [ ]:
#Vector Sine Angle and Cross Product


In [16]:
c = np.cross(a, b)
c

array([-1, -4,  3])

In [17]:
c_mag = np.linalg.norm(c)
c_mag

5.0990195135927845

In [18]:
amag = np.linalg.norm(a)
bmag = np.linalg.norm(b)

In [19]:
sin_angle = c_mag / ( amag * bmag)
sin_angle

0.1573591584938886

In [20]:
sinangle = np.arcsin(sin_angle)  ## inverse sin value
sinangle

0.15801592211305715

In [32]:
mat1 = ([1,2,4],[3,4,5])
mat2 = ([3, 4, 6],[5, 6, 7],[6,56, 7])
 

res = np.dot(mat1,mat2)
 
res

array([[ 37, 240,  48],
       [ 59, 316,  81]])

In [30]:
mat3 =([1,2,3],[4,5,6])
mat4 =([4,5,6],[1,2,3])
res1 = np.cross(mat3,mat4)

In [31]:
res1

array([[-3,  6, -3],
       [ 3, -6,  3]])

In [33]:
#assignment 
#learn about singular value decomposition(SVDs)
## SVD is a factorization of a real or complex matrix. 

4.0

6.0